[build-system]
requires = ["scikit-build-core>=0.10", "nanobind>=2.12"]
build-backend = "scikit_build_core.build"

[project]
name = "drambender"
version = "0.1.0"
description = "Python and C++ interface for DRAM-Bender"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["numpy>=1.26"]

[tool.scikit-build]
minimum-version = "build-system.requires"
wheel.packages = ["python/drambender"]
install.components = ["python"]
build.targets = ["drambender_core"]

[tool.scikit-build.cmake.define]
BUILD_TESTING = "OFF"
DRAMBENDER_BUILD_PYTHON = "ON"
DRAMBENDER_BUILD_EXAMPLES = "OFF"
DRAMBENDER_BUILD_BOARD_TESTS = "OFF"
DRAMBENDER_BUILD_BOARD_BENCHMARKS = "OFF"
