PACKAGE_NAME="drambender-xdma"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="drambender_xdma"
BUILT_MODULE_LOCATION[0]="xdma"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="make -C xdma KVER=\${kernelver}"
CLEAN="make -C xdma KVER=\${kernelver} clean"
AUTOINSTALL="yes"
