######################################################################
#
# File name : sim_tb_top_wave.do
# Created on: Wed Aug 24 11:25:36 CEST 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
