######################################################################
#
# File name : sim_tb_top_simulate.do
# Created on: Wed Aug 31 17:31:36 CEST 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim +notimingchecks -onfinish final -lib xil_defaultlib sim_tb_top_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {sim_tb_top_wave.do}

view wave
view structure
view signals

log -r /*

do {sim_tb_top.udo}

run 60000ns
