#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Mentor Graphics Questa Advanced Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Aug 31 17:31:36 CEST 2022
# SW Build 3080587 on Fri Dec 11 14:53:26 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
bin_path="/usr/pack/questa-2020.1-kgf/questasim/bin"
set -Eeuo pipefail
$bin_path/vsim -64  -do "do {sim_tb_top_simulate.do}" -l simulate.log

